---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest    
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000    

  kafka:
    image: confluentinc/cp-kafka:latest 
    ports:
      - "29092:29092"
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092     
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
               
  processor:
    image: maliska/payslip-processing:latest
    ports:
        - "8082:8082"
    #links:
    #  - kafka
    depends_on:
      - kafka
    environment:      
      - bootstrap.servers=localhost:39092 
       
    network_mode: host
    
  fulfilment:
    image: maliska/payslip-fulfilment:latest
    ports:
      - "8081:8081"
    #links:
    #  - kafka
    depends_on:
      - kafka
    environment:     
      bootstrap.servers: localhost:39092         
      
    network_mode: host  
      

  