---
version: '3'

volumes:  
  kafka_data:
    driver: local
  kafka_secret:
    driver: local
  zk_data:
    driver: local
  zk_secret:
    driver: local
  zk_log:
    driver: local
  control_center_data:
    driver: local    
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
    
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks: 
      - paynet
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
        - zk_data:/var/lib/zookeeper/data
        - zk_secret:/etc/zookeeper/secrets
        - zk_log:/var/lib/zookeeper/log
    ports:
      - "32181:2181"
   
  kafka:
    image: confluentinc/cp-kafka:latest  
    container_name: kafka
    networks: 
     - paynet
    depends_on:
      - zookeeper
    links:
     - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 15728640   
    ports:
      - "29092:9092"
    volumes:
        - kafka_data:/var/lib/kafka/data
        - kafka_secret:/etc/kafka/secrets
        
  #control_center:
  #  image: confluentinc/cp-control-center:latest
  #  container_name: control_center
  #  networks:
  #    - paynet
  #  depends_on:
  #    - zookeeper
  #    - kafka
  #  environment:
  #   CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:32181
  #    CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:29092
  #    CONTROL_CENTER_REPLICATION_FACTOR: 1
  #    CONTROL_CENTER_CONNECT_CLUSTER: http://control_center:28082
  #  ports:      
  #    - "9021:9021"
  #  volumes:
  #     # - /mnt/control-center/data:/var/lib/confluent-control-center
  #      - control_center_data:/var/lib/confluent-control-center
  mongo_db:
    image: mongo:latest 
    container_name: mongo_db 
    ports:
      - "27017:27017"    
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb    
    networks:
      - paynet
networks:
    paynet:
        external: true     
  