version: '2'
services:
  processor:
    image: maliska/payslip-processing:latest
    ports:
        - "8082:8082"
    environment:
      - bootstrap.servers=kafka      
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      - paynet
  fulfilment:
    image: maliska/payslip-fulfilment:latest
    ports:
      - "8081:8081"
    environment:
      - bootstrap.servers=kafka      
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      - paynet   
  kafka:
    image: spotify/kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - TOPICS=payslips
      - ZK_CONNECT='kafka:2181'
networks:
  paynet:
    external: true
            
    

