version: '2'
services:
  processor:
    image: nnpc/payslip-processing:1.0.0
    container_name: request_processor
    #restart: always    
    #ports:
    #  - "8082:8082"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
    #  - EWS_HOST=mail.nnpcgroup.com
      - EWS_USER=18359
      - EWS_PASSWORD=M@dan1sco
    #  - EWS_DOMAIN=chq
    networks:
      - paynet      
    
  fulfilment:
    image: nnpc/payslip-fulfilment:1.0.0
    #container_name: request_fulfilment
    #restart: always
    #ports:
    #  - "8081:8081"
    environment:           
      - BOOTSTRAP_SERVERS=kafka:29092   
      - mongodb.url=mongodb://mongo_db   
      - JCO_ASHOST=10.0.64.111
      - JCO_CLIENT=500
      - JCO_USER=PAYSLP_AGENT
      - JCO_PASSWD=Password@1      
    networks:
      - paynet
      
  notification:
    image: nnpc/payslip-notification:1.0.0 
    #container_name: request_fulfilment
    #restart: always
    #ports:
    #  - "8081:8081"
    environment:           
      - BOOTSTRAP_SERVERS=kafka:29092     
      - mongodb.url=mongodb://mongo_db   
      #- EWS_HOST=mail.nnpcgroup.com
      - EWS_USER=18359
      - EWS_PASSWORD=M@dan1sco
    #  - EWS_DOMAIN=chq
      - AGENT_EMAIL=ayemi.musa@nnpcgroup.com      
    networks:
      - paynet
      
networks:
    paynet:
        external: true
       

    

