version: '2'
services:
  processor:
    image: maliska/payslip-processing:latest
    ports:
        - "8082:8082"
    environment:
      - bootstrap.servers=kafka      
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      - paynet
  fulfilment:
    image: maliska/payslip-fulfilment:latest
    ports:
      - "8081:8081"
    environment:
      - bootstrap.servers=kafka      
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      - paynet   
  kafka:
    image: confluent/kafka
    ports:
      - "9092:9092"  
    environment:      
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    links:
      - zookeeper
    networks:
      - paynet 
      
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181" 
    networks:
      - paynet 
    
networks:
  paynet:
    external: true
            
    

#docker run -d --name zookeeper -p 2181:2181 confluent/zookeeper
#docker run -d --name kafka -p 9092:9092 --link zookeeper:zookeeper confluent/kafka
#docker run -d --name kafka -p 9092:9092 --link zookeeper:zookeeper --env KAFKA_ADVERTISED_HOST_NAME=$DOCKER_MACHINE confluent/kafka
