version: '2'
services:
  processor:
    image: maliska/payslip-processing:latest 
    container_name: request_processor
    #restart: always    
    #ports:
    #  - "8082:8082"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - paynet      
    
  fulfilment:
    image: maliska/payslip-fulfilment:latest 
    #container_name: request_fulfilment
    #restart: always
    #ports:
    #  - "8081:8081"
    environment:           
      - BOOTSTRAP_SERVERS=kafka:29092   
      - mongodb.url=mongodb://mongo_db   
      - JCO_ASHOST=10.0.64.111
      - JCO_CLIENT=500
      - JCO_USER=18359
      - JCO_PASSWD=M@dan1sc0      
    networks:
      - paynet
      
  notification:
    image: maliska/payslip-notification:latest 
    #container_name: request_fulfilment
    #restart: always
    #ports:
    #  - "8081:8081"
    environment:           
      - BOOTSTRAP_SERVERS=kafka:29092     
      - mongodb.url=mongodb://mongo_db      
    networks:
      - paynet
      
networks:
    paynet:
        external: true
       

    

