// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.payslip.subscription;

import java.util.Objects;

import jakarta.annotation.Nonnull;


/**
 * Represents a subscription created by the application
 */
public class SubscriptionRecord {

    /**
     * The subscription ID returned by Microsoft Graph when the subscription is created
     */
    public final String subscriptionId;

    /**
     * For delegated auth, this is the user's ID used to create the subscription. For app-only auth,
     * this is "APP-ONLY"
     */
    public final String userId;

    /**
     * The client state value used to create the subscription. All notifications generated by this
     * subscription MUST send this value
     */
    public final String clientState;

    public SubscriptionRecord(@Nonnull final String subscriptionId, @Nonnull final String userId,
            @Nonnull final String clientState) {
        this.subscriptionId = Objects.requireNonNull(subscriptionId);
        this.userId = Objects.requireNonNull(userId);
        this.clientState = Objects.requireNonNull(clientState);
    }
}
