---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: processor
  namespace: comd
spec:  
  replicas: 1
  template:
    metadata:
      labels:
        app: processor
        tier: background
    spec:
      hostname: processor
      containers:
        - name: request-processor
          image: maliska/payslip-processing:latest
          imagePullPolicy: IfNotPresent
        #resources:
        #  requests:
        #  cpu: 100m
        #  memory: 100Mi
          env:
          - name: BOOTSTRAP_SERVERS
            value: kafka:29092 
          ports:
          - containerPort: 8082