apiVersion: batch/v1
kind: Job
metadata:
  name: topics-payslips
  namespace: comd
spec:
  template:
    metadata:
      name: topics-payslips
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        command: ["kafka-topics"]
        args: ["--create", "--topic", "payslips", "--partitions", "1", "--replication-factor", "3", "--if-not-exists", "--zookeeper", "zookeeper:32181"]
      restartPolicy: Never
