---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: comd
spec:
  ports:
  - port: 32181
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: comd
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest 
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        ports:
        - containerPort: 32181
